"""Notification event model — stores structured events generated by the pipeline."""

import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, Integer, Text, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base


class NotificationEvent(Base):
    __tablename__ = "notification_events"

    id: Mapped[str] = mapped_column(
        String, primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Event classification
    event_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    confidence: Mapped[int] = mapped_column(Integer, nullable=False, default=50)

    # Structured notification content
    situation: Mapped[str] = mapped_column(Text, nullable=False)
    impact: Mapped[str] = mapped_column(Text, nullable=False)
    recommended_action: Mapped[str] = mapped_column(Text, nullable=False)

    # Farm/zone targeting
    farm_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    zone_id: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Rich context
    risk_scores: Mapped[dict] = mapped_column(JSONB, default=dict)
    source_data: Mapped[dict] = mapped_column(JSONB, default=dict)

    # Dedup hash for spam prevention
    dedup_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
